services:
  yuan_model:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: ./models/yuan_model/requirements.txt
        MODEL_NAME: yuan
    env_file:
      - path: ./.env
    environment:
      PORT: 6666
      HOST: 0.0.0.0
    ports:
      - 6666:6666
    networks:
      - bot
  vincent_model:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: ./models/vincent_model/requirements.txt
        MODEL_NAME: vincent
    env_file:
      - path: ./.env
    environment:
      PORT: 6666
      HOST: 0.0.0.0
    networks:
      - bot
  #  paul_model:
  #    build:
  #      context: .
  #      args:
  #        REQUIREMENTS_FILE: ./models/paul_model/requirements.txt
  #        MODEL_NAME: paul
  #    env_file:
  #      - path: ./.env
  #    environment:
  #      PORT: 6666
  #      HOST: 0.0.0.0
  #    networks:
  #      - bot

networks:
  bot:
