services:
  yuan_model:
    image: ghcr.io/yuntechai-freespacetechnic/runtime:latest
    hostname: modelserver_${MODEL_NAME}
    environment:
      APP_PATH: server.py
      APP_ARGS: ${MODEL_NAME} ${HOST} ${PORT}
    volumes:
      - ./models/${MODEL_NAME}_model:/usr/src/app/${MODEL_NAME}_model
      - ./server.py:/usr/src/app/server.py
      - ./common/:/usr/src/app/common/
    env_file:
      - path: ./env/${MODEL_NAME}.env
    networks:
      - modelserver
  vincent_model:
    image: ghcr.io/yuntechai-freespacetechnic/runtime:latest
    hostname: modelserver_${MODEL_NAME}
    environment:
      APP_PATH: server.py
      APP_ARGS: ${MODEL_NAME} ${HOST} ${PORT}
    volumes:
      - ./models/${MODEL_NAME}_model:/usr/src/app/${MODEL_NAME}_model
      - ./server.py:/usr/src/app/server.py
      - ./common/:/usr/src/app/common/
    env_file:
      - path: ./env/${MODEL_NAME}.env
    networks:
      - modelserver
  # paul_model:
  #   image: ghcr.io/yuntechai-freespacetechnic/runtime:latest
  #   hostname: modelserver_${MODEL_NAME}
  #   environment:
  #     APP_PATH: server.py
  #     APP_ARGS: ${MODEL_NAME} ${HOST} ${PORT}
  #   volumes:
  #     - ./models/${MODEL_NAME}_model:/usr/src/app/${MODEL_NAME}_model
  #     - ./server.py:/usr/src/app/server.py
  #     - ./common/:/usr/src/app/common/
  #   env_file:
  #     - path: ./env/${MODEL_NAME}.env
  #   networks:
  #     - modelserver

networks:
  modelserver:
    name: modelserver
